export const nameMap: {[key: string]: string} = {
    date: 'Dátum',
    name: 'Név',
    address: 'Lakcím',
    taxID: 'Adóazonosító szám',
    originID: 'Származási Ig. Szám',
    HLF: 'Hektoliterfok',
    weightInKilograms: 'Tömeg',
    Dátum: 'date',
    Név: 'name',
    Lakcím: 'address',
    'Adóazonosító szám': 'taxID',
    'Származási Ig. Szám': 'originID',
    Hektoliterfok: 'HLF',
    Tömeg: 'weightInKilograms',
}